### PR TITLE
fix(#10): Create README.md

### PR DESCRIPTION
**Pull request by Atem18**
It fixes https://github.com/git-for-windows/git-sdk-64/issues/10

### CODE REVIEW

**Comment by dscho** [comment]
Is this really a good README? Does it answer what this is all about?

I don't think so. It does not say what the purpose of the Git for Windows SDK is (or more appropriately, _the purposes_), it does not talk about MSYS2, it does not talk about `pacman`, it does not talk about the Azure Pipeline that keeps this repository up to date, and it does not talk about the `sdk` function.

That's quite a lot of information that it does not talk about, quite a lot of information that however would be super useful to talk about in a `README`.

Further, the commit message (apart from following the GitFlow convention I personally quite detest) is not helpful, either. It does not talk about anything, it only references a ticket (twice, to add insult to injury). In the _least_ it could copy-edit https://github.com/git-for-windows/git-sdk-64/issues/10#issue-487768482.

What do you think? Can you improve this PR?

**Comment by Atem18** [comment]
@dscho Sure, I was just copying the other commit but if you want an improvement, I will do.

**Comment by dscho** [comment]
> I was just copying the other commit

I am not proud of that commit. Would you mind improving that one, too?

**Comment by Atem18** [comment]
@dscho I was speaking about that commit : https://github.com/git-for-windows/git-sdk-64/pull/8/commits

Which one are you referring to ?

**Comment by dscho** [comment]
> Which one are you referring to ?

The same.

**Pull request closed without merging**
