### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by PhilipOakley**
The README will also be added to the contributors top level directory
providing details of where the SDK repository is located, and how the installer
is generated, to aid their debugging of update failures and other issues

Signed-off-by: Philip Oakley <philipoakley@iee.email>

### CODE REVIEW

**Review by dscho — COMMENTED** [review]
Thank you for starting this.

After reading through your proposed `README`, I have to admit, though, that it leaves me with the feeling that its focus should be modified.

Granted, _what_ it says is not wrong per se, it's just not very interesting to the majority of likely readers.

Like, yes, there is a subdirectory in a repository that contains the definition for the SDK installer. But the person who cloned the SDK repository is very unlikely to have the need or desire to rebuild the installer at that point.

Likewise, yes, sure, the installer is a self-extracting 7-Zip archive. But is that really interesting to the user?

Then, as a total non-sequitur, the `README` tells the user about a script that uses `pacman`.

If I put myself into the shoes of a totally new user, I would be very confused by all this:
- I would wonder what the purpose of the SDK is?
- I would not have learned about the `sdk` shell function, the convenient helper designed to facilitate pretty much everything a Git for Windows SDK user might want to do.
- It would be totally unclear to me that the most interesting location in the SDK is `/usr/src/`.
- I would wonder where all those files originate from, surely the SDK cannot be the source of truth, right? The `README` _does_ mention -- in passing -- that this repository is "mirroring the current 64-bit Git for Windows SDK". But from _where_? Where is the _actual_ SDK?
- I would not have learned about the package management.
- I would not have learned that Git for Windows' installer (just like the other release artifacts) is built from a subset of the SDK.
- I would not have read anything about MSYS2, Cygwin, Pacman, and how they relate to the SDK.
- I would not have learned that there is an Azure Pipeline building the `git-sdk-64-minimal` artifact that is used by Git's CI builds.
- I would not have learned that there is the `git-for-windows/setup-git-for-windows-sdk` GitHub Action for use in workflows.

So I think that this will need a major rewrite.

**Comment by PhilipOakley** [comment]
Hi @dscho,

I think you missed the point. This was written because the points that I included were those I found were awkward to find, given an already installed SDK. 

Remember the standard entry point to use of the SDK is NOT by cloning the repo. It's either via the Git-for-Windows home page's 'Contribute' link, or via a link we (you typically) have provided to get folks started quickly. 

Thus contributors have the SDK installed, but never personally cloned it, so the ReadMe here acts as a set of small clues to reverse 'find' where everything came from, when things go 'wrong'.

What you ask for can easily be added later. Maybe your list could be added as extra ToDo points.

**Comment by dscho** [comment]
> I think you missed the point.

Umm, okay, then.

> This was written because the points that I included were those I found were awkward to find, given an already installed SDK.

So you wanted to start an FAQ, like.

> Remember the standard entry point to use of the SDK is NOT by cloning the repo

I should point out, however, that cloning the repo is [exactly what the SDK installer does](https://github.com/git-for-windows/build-extra/blob/3126a11ae9fd6c979d8e94f29b605e0151b4503f/sdk-installer/setup-git-sdk.bat#L16).

So you will have that beautiful `README.md` right there, in the top-level directory, answering _your_ questions (but not the questions most other SDK users will have).

> What you ask for can easily be added later.

You got that backwards.

You can easily add those answers to the existing FAQ, or start a new one on the wiki.

What you put into that `README` is not material for a `README`. It is better to have no `README` than to have a `README` that confuses the readers and leaves all of their questions open.

Please do not make the mistake of assuming that other SDK users will have the same questions as you do. In fact, given the evidence on Git for Windows' bug tracker, you actually know what the usual questions are, and [I summarized some of them in the earlier comment](https://github.com/git-for-windows/git-sdk-64/pull/42#pullrequestreview-796246689) that you so elegantly tried to brush aside.

**Comment by PhilipOakley** [comment]
OK I'll leave it for others then.

**Pull request closed without merging**
