### PR TITLE
 Add a CI definition to build Git for Windows' artifacts continuously

### PR DESCRIPTION
**Pull request by dscho**
Every once in a while, Git for Windows' release automation gets broken e.g. by package updates.

This new workflow is designed to catch such issues early, so that we do not have to scramble frantically to fix such problems on the day we need to release a new Git for Windows version.

This is a companion to https://github.com/git-for-windows/git-sdk-32/pull/16

### CODE REVIEW

**Comment by dscho** [comment]
One funny thing I noticed while developing these patches is that the 64-bit installer takes [about 5 minutes to install](https://github.com/dscho/git-sdk-64/runs/8129659099?check_suite_focus=true#step:9:1) while the 32-bit installer only takes [about 45 seconds](https://github.com/dscho/git-sdk-32/runs/8131100815?check_suite_focus=true#step:10:1).

I've changed the definition so that it uploads the installer log (which contains timestamps), and started [a new run](https://github.com/dscho/git-sdk-64/actions/runs/2970725298). Hopefully those logs will reveal where that difference comes from.

**Comment by rimrul** [comment]
> I've changed the definition so that it uploads the installer log (which contains timestamps), and started [a new run](https://github.com/dscho/git-sdk-64/actions/runs/2970725298). Hopefully those logs will reveal where that difference comes from.

That new run took only 57s, so I'd  chalk it up to CI runner host utilization, unless we run into more issues with that.

**Comment by dscho** [comment]
> I've changed the definition so that it uploads the installer log (which contains timestamps), and started [a new run](https://github.com/dscho/git-sdk-64/actions/runs/2970725298). Hopefully those logs will reveal where that difference comes from.

Turns out that the 5 minutes might simply have been an outlier. In this run, it took [57 seconds to install](https://github.com/dscho/git-sdk-64/runs/8133187219?check_suite_focus=true#step:9:1). So now all is good, I force-pushed 3054214024 (the commit to allow this workflow to run in my fork) away, and will now mark the PR to be ready for review.

**Comment by dscho** [comment]
> That new run took only 57s, so I'd chalk it up to CI runner host utilization, unless we run into more issues with that.

I swear I looked for answers before posting my reply... 😦 

So you independently found the same thing as I did, which is great!

**Pull request merged**
